name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
      


    - name: Open directory & Test with Gradle Wrapper
      run: |
        cd ./CandyCrushIntelliJProject
        ls -la
        chmod +x gradlew
        ./gradlew test

